<?php
    /**
     * Implements hook_preprocess_block().
     */
    function dataportaal_preprocess_node(&$variables) {

      $variables['host'] = str_replace("cms.", "", \Drupal::request()->getSchemeAndHttpHost() );

    }

		/**
		 * Implements hook_form_alter().
		 */
		function dataportaal_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
		  $form['revision_information']['#access'] = FALSE;
		}
